# Generated by Django 5.0.1 on 2024-04-12 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='camera_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('camerano', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='notification_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('image', models.FileField(upload_to='')),
                ('type', models.CharField(max_length=100)),
                ('CAMERA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forest_app.camera_table')),
            ],
        ),
        migrations.CreateModel(
            name='notistatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forest_app.login_table')),
                ('nid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forest_app.notification_table')),
            ],
        ),
        migrations.CreateModel(
            name='officer_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forest_app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_app_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=1000)),
                ('OFFICER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forest_app.officer_table')),
            ],
        ),
        migrations.CreateModel(
            name='report_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('OFFICER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forest_app.officer_table')),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forest_app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.CharField(max_length=1000)),
                ('reply', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('OFFICER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forest_app.officer_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forest_app.user_table')),
            ],
        ),
    ]
